### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by tomberek** [Ekleog/nixpkgs-check#10] opened 2021-03-28 17:57 UTC
Not sure the cause, could be i'm using it wrong:
```
[tom@tom:~/nixpkgs-check]$ ./result/bin/nixpkgs-check -b master --repo-path ~/nixpkgs refs/remotes/origin/pull/117637/head
✔ which packages do you want to test? · parallel
✔ what other packages do you want to test? [empty to stop] ·
✔ on what machines did you already attempt building? [space to select, enter to validate] ·
✔ what other manual tests did you run? [empty to stop] ·
running base version of environment
running base version of ask-package-names
running base version of ask-other-tests
running to-check version of environment
running to-check version of ask-package-names
running to-check version of ask-other-tests
running base version of build(parallel)
error: '((import ./. { overlays = []; }).parallel)' is not a valid URL
running to-check version of build(parallel)
error: '((import ./. { overlays = []; }).parallel)' is not a valid URL
pruning the no-longer-existing worktrees


Report to be pasted in the PR message
-------------------------------------

### nixpkgs-check report

**version:** `nixpkgs-check v0.1.0` on NixOS 21.05.20210319.f5e8bdd with sandboxing
**packages declared changed:** {"parallel"}
**manual tests declared performed:**
 * 😢 not built on NixOS
 * 😢 not built on MacOS
 * 😢 not built on Other Linux distributions

**package parallel:** 😢 still does not build
```

**Comment by Ekleog** [comment] 2021-03-29 22:23
Hmmm this is interesting… I wonder whether the `nix` API changed? But then you're on exactly the same commit of nixpkgs as I'm testing on, so… weird. Can you just confirm that `nix --version` is 2.3.10 at your place too?

(I had to use the new command line for `nix path-info -S`, and thus went with `nix build` too so as to get better output as I have to rely on the unstable CLI anyway, but…)

What's weird is, me doing the same thing does manage to build. And you're using it correctly, though the `-b master` is not necessary as it's the default value.

I've just pushed an update to make `nix` be used from a wrapper instead of from the environment. Does nix manage to build thing on your machine now?

**Comment by Ekleog** [comment] 2021-03-29 22:26
Ooh. Actually: maybe you're using `nixFlakes`? I'm thinking this might be due to something like the `nix build` CLI being changed to default to flakes-building. In this case, it'd be looking for a flake URL instead of the previous syntax, that allowed parenthesized expressions too.

If this is true, then the recent commit that now takes `nix` from a known-good nixpkgs checkout should probably solve the issue :)

**Comment by tomberek** [comment] 2021-03-30 01:12
Yes, I'm on nixFlakes.

**Comment by Ekleog** [comment] 2021-04-08 22:10
With the latest changes this was confirmed failing-before working-after with nixFlakes, so I'm going to close this, thank you for the report :)

**Closed as completed by Ekleog** 2021-04-08 22:10 UTC
